SimplePhotoMemo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^profile/$', views.profile_detail, name='profile_detail'),
    url(r'^signup/$', views.SignupFormView.as_view(), name='signup'),
    url(r'^login/$', login, name='login', kwargs={'template_name': 'accounts/login.html'}),
    url(r'^logout/$', logout, name='logout', kwargs={'next_page': settings.LOGIN_URL}),
]

post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.memo_list , name='memo_list'),
    url(r'^memo/create/$', views.memo_create, name='memo_create'),
    url(r'^memo/(?P<pk>\d+)/$', views.memo_detail, name='memo_detail'),
    url(r'^memo/(?P<pk>\d+)/edit/$', views.memo_edit, name='memo_edit'),
    url(r'^memo/(?P<pk>\d+)/delete/$', views.memo_delete, name='memo_delete'),

]

accounts/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    address = models.CharField(max_length=100)
    sns = models.URLField()

post/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse


from imagekit.models import ImageSpecField
from imagekit.processors import Thumbnail

# Create your models here.

class Memo(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=50, verbose_name='제목')
    content = models.TextField(verbose_name='내용')

    photo = models.ImageField(blank=True, upload_to='post/memo/%Y/%m/%d')
    photo_thumbnail = ImageSpecField(
                            source='photo',
                            processors=[Thumbnail(300, 300)],
                            format='JPEG',
                            options={'quality': 60})
    tag_set = models.ManyToManyField('Tag', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:memo_detail', args=[self.pk])

    class Meta:
        ordering =['-id']

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL) #user
    post = models.ForeignKey(Memo) #post_id 생성
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Profile

class SignupForm(UserCreationForm):
    sns = forms.URLField()
    address = forms.CharField()

    def save(self):
        user = super().save()
        Profile.objects.create(
            user=user,
            sns=self.cleaned_data['sns'],
            address=self.cleaned_data['address'],
        )
        return user

post/forms.py
from django import forms
from .models import Memo

class MemoCreateForm(forms.ModelForm):

    class Meta:
        model = Memo
        fields = ['author','title', 'content', 'photo']

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView as AuthLoginView
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.conf import settings
from django.views.generic.edit import CreateView

from .forms import SignupForm

# Create your views here.

class SignupFormView(CreateView):
    form_class = UserCreationForm
    template_name = 'accounts/signup_form.html'
    success_url = settings.LOGIN_URL

class LoginView(AuthLoginView):
    pass

@login_required
def profile_detail(request):
    return render(request, 'accounts/profile_detail.html')


# def signup(request):
#     if request.method == 'POST':
#         form = SignupForm(request.POST, request.FILES)
#         if form.is_valid():
#             user = form.save()
#             return redirect(settings.LOGIN_URL)
#     else:
#         form = SignupForm()
#     return render(request, 'accounts/signup_form.html', {
#         'form' : form
#     })

post/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, resolve_url
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from .models import Memo
from .forms import MemoCreateForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.


def memo_list(request):
    memo_qs = Memo.objects.all()
    paginator = Paginator(memo_qs, 9)

    page = request.GET.get('page',1)

    try:
        memo_lst = paginator.page(page)
    except PageNotAnInteger:
        memo_lst = paginator.page(1)
    except EmptyPage:
        memo_lst = paginator.page(paginator.num_pages)


    return render(request, 'post/memo_list.html', {
        'memo_list': memo_lst,
    })

class MemoCreateView(CreateView):
    model = Memo
    form_class = MemoCreateForm

memo_create = MemoCreateView.as_view()


class MemoDetailView(DetailView):
    model = Memo

memo_detail = MemoDetailView.as_view()


class MemoUpdateView(UpdateView):
    model = Memo
    fields = ['__all__']

memo_edit = MemoUpdateView.as_view()

class MemoDeleteView(DeleteView):
    model = Memo

    def get_success_url(self):
        return resolve_url(self.object.memo)

memo_delete = MemoDeleteView.as_view()

SimplePhotoMemo/templates/layouts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}main{% endblock %}</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css"/>
    <link rel="stylesheet" href="{% static "semantic/dist/semantic.min.css" %}"/>
    {% block styles %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url "post:memo_list" %}">SimpleMemoApp</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url "post:memo_list" %}">Memo</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url "post:memo_create" %}" class="btn btn-default">New Memo</a>
                {% if user.is_authenticated %}
                    <li><a href="{% url "accounts:profile_detail" %}">프로필</a></li>
                    <li><a href="{% url "accounts:logout" %}?next={{ request.path }}">로그아웃</a></li>
                {% else %}
                    <li><a href="{% url "accounts:login" %}?next={{ request.path }}">로그인</a></li>
                    <li><a href="{% url "accounts:signup" %}">회원가입</a></li>
                {% endif %}
        </ul>
      </div>
    </nav>

    {% block content %}
    {% endblock %}

</body>
<script src="{% static "jquery/dist/jquery.min.js" %}"></script>
<script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
<script src="{% static "semantic/dist/semantic.min.js" %}"></script>
{% block scripts %}{% endblock %}

</html>

accounts/templates/accounts/layouts.html
{% extends "layouts.html" %}

{% block title %}프로필{% endblock %}

accounts/templates/accounts/login.html
{% extends "accounts/layouts.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary" value="로그인">
            </form>
        </div>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/profile_detail.html
{% extends "accounts/layouts.html" %}

{% block content %}
    <h2>
        {{ user }}'s Profile
    </h2>
    <ul>
        <li>username : {{ user.username }}</li>
        <li>email : {{ user.email }}</li>
        <li>date_joined : {{ user.date_joined }}</li>
    </ul>

{#    <img src="{{ user.socialaccount_set.all.first.get_avatar_url }}" />#}
{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends "accounts/layouts.html" %}
{% load bootstrap3 %}

{% block title %} 회원가입 {% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form action="" method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" class="btn btn-primary" value="회원가입">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

post/templates/post/comment_form.html
{% extends "blog/layout.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">

        <form action="" method="post">
            {% csrf_token %}
{#            <table class="table table-hover table-bordered">#}
{#                {{ form.as_table }}#}
{#            </table>#}
            {% bootstrap_form form %}

            <input type="submit">
        </form>
        </div>
    </div>
</div>
{% endblock %}

post/templates/post/layouts.html
{% extends "layouts.html" %}

post/templates/post/memo_confirm_delete.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">

        <form action="" method="post">
            {% csrf_token %}
            <p class="alert alert-danger">
                정말 삭제하시겠습니까?
            </p>
            <input type="submit" value="삭제" class="btn btn-danger" />
        </form>

        </div>
    </div>
</div>

{% endblock %}

post/templates/post/memo_detail.html
{% extends "post/layouts.html" %}
{% load imagekit %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>{{ memo.title }}</h2>
                <h5><span class="glyphicon glyphicon-time"></span> Post by {{ memo.author }}, {{ memo.created_at }}</h5>
                <h5><span class="label label-danger">Food</span> <span class="label label-primary">Ipsum</span></h5><br>

                {% thumbnail "500x500" memo.photo -- class="img-thumbnail center-block" %}
                <br><br>

                <p style="font-size:15px;">{{ memo.content }}</p>

                <br><br>
                <hr />
                    <a href="{% url "post:memo_list" %}" class="btn btn-primary">목록</a>
                    <a href="#" class="btn btn-primary">수정</a>
                    <a href="#" class="btn btn-primary">삭제</a>
                <hr />
            </div>
        </div>
    </div>

{% endblock %}

post/templates/post/memo_form.html
{% extends "post/layouts.html" %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" value="저장">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

post/templates/post/memo_list.html
{% extends "post/layouts.html" %}
{% load imagekit %}
{% load static %}
{% block content %}
    <div class="container">
        <div class="row">
        <div class="col-sm-12">
            {% for memo in memo_list %}
                <div class="col-sm-4">
                    <div class="ui card">
                        <a class="image" href="{% url "post:memo_detail" memo.pk %}">
                            {% if memo.photo %}
                                {% thumbnail "200x200" memo.photo %}
                            {% else %}
                                <div align="center">
                                    <img src="{% static "img/none.png" %}" style="width:200px;height:200px"/>
                                </div>
                            {% endif %}
                        </a>
                        <div class="content">
                            <a class="header" href="{% url "post:memo_detail" memo.pk %}">{{ memo.title }}</a>
                            <div class="meta">
                                <a><small>by.</small>{{ memo.author }}</a>
                            </div>
                        </div>
                    </div>
                    <br>
                </div>
            {% endfor %}


        {#    pagenation part   #}
        {% if memo_list.has_other_pages %}
            <div class="center-block">
                <ul class="pagination">
                {% if memo_list.has_previous %}
                    <li><a href="?page={{ memo_list.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}

                {% for i in memo_list.paginator.page_range %}
                    {% if memo_list.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if memo_list.has_next %}
                    <li><a href="?page={{ memo_list.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
            </div>
        {% endif %}
        </div>
       </div>
    </div>
{% endblock %}